[[cookies]]
id = "cranberry-pistachio"
year = 2024
name = "Brown Butter Slice"
description = "Cranberry + pistachio + white chocolate"
image_url = "/images/cranberry-pistachio.png"

[[cookies]]
id = "rye-chocolate-hazelnut-praline"
year = 2024
name = "Rye Chocolate Chip"
description = "Hazelnut praline + 70% dark chocolate"
image_url = "/images/rye-chocolate-hazelnut-praline.png"

[[cookies]]
id = "pecan-snowball"
year = 2024
name = "Pecan Snowball"
description = "Vanilla bean + toasted pecan"
image_url = "/images/pecan-snowball.png"

[[cookies]]
id = "apple-caramel-sandwich"
year = 2024
name = "Apple Sandwich"
description = "Freeze dried apple + cider caramel"
image_url = "/images/apple-caramel-sandwich.png"

[[cookies]]
id = "lemon-curd-stuffed"
year = 2024
name = "Lemon Curd Stuffed"
description = "Poppyseed + zest of 10 lemons"
image_url = "/images/lemon-curd-stuffed.png"

[[cookies]]
id = "spruce-strawberry-thumb"
year = 2024
name = "Forest Thumbprint"
description = "Summer strawberry + wild spruce tip"
image_url = "/images/spruce-strawberry-thumb.png"

[[cookies]]
id = "cranberry-pistachio"
year = 2025
name = "Brown Butter Slice"
description = "Cranberry + pistachio + white chocolate"
image_url = "/images/cranberry-pistachio.png"

[[cookies]]
id = "miso-toffee-chocolate-chip"
year = 2025
name = "Miso Toffee Chocolate Chip"
description = "Brown butter + 70% dark chocolate"
image_url = "/images/miso-toffee-chocolate-chip.png"

[[cookies]]
id = "roasted-shortbread"
year = 2025
name = "Roasted Shortbreads"
description = "Toasted rye flour + cultured butter"
image_url = "/images/roasted-shortbread.png"

[[cookies]]
id = "wasabi-pepparkakor"
year = 2025
name = "Wasabi Pepparkakor"
description = "Mörk sirap + ginger"
image_url = "/images/wasabi-pepparkakor.png"

[[cookies]]
id = "pear-softie"
year = 2025
name = "Pear Softies"
description = "Rosemary + vanilla bean"
image_url = "/images/pear-softie.png"

[[cookies]]
id = "chocolate-sable"
year = 2025
name = "Very Chocolatey Sablé"
description = "Cocoa nibs + freeze dried raspberries"
image_url = "/images/chocolate-sable.png"
